# Use an existing docker image as a base
FROM python:3.11

# Change the default shell to /bin/sh
SHELL ["/bin/sh", "-c"]
RUN apt-get update && apt-get install -y bash

# Install the necessary packages
RUN pip install langchain openai meilisearch python-dotenv
